# Generated by Django 5.1.1 on 2024-10-17 20:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Seleccione una imágen para mostrar', null=True, upload_to='img/posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 20, 56, 12, 582405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='posts',
            name='categorias',
            field=models.ManyToManyField(related_name='posts', to='blog.categoria'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo_comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 10, 17, 20, 56, 12, 584413, tzinfo=datetime.timezone.utc))),
                ('aprobado', models.BooleanField(default=False)),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='blog.posts')),
            ],
        ),
    ]
