# Generated by Django 5.1.1 on 2024-10-20 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_posts_contenido_posts_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 19, 36, 58, 814920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, help_text='Seleccione una imágen para mostrar', null=True, upload_to='img/posts')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 10, 20, 19, 36, 58, 813920, tzinfo=datetime.timezone.utc))),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(related_name='Post', to='blog.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='blog.post'),
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
