# Generated by Django 5.1.1 on 2024-10-23 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comentario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 22, 2, 54, 797264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 22, 2, 54, 796264, tzinfo=datetime.timezone.utc)),
        ),
    ]
