# Generated by Django 5.1.1 on 2024-10-27 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 0, 2, 14, 310915, tzinfo=datetime.timezone.utc)),
        ),
    ]
