# Generated by Django 5.1.1 on 2024-10-27 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 15, 19, 36, 370633, tzinfo=datetime.timezone.utc)),
        ),
    ]
